apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: janicemumbua/ip2:v1.0.0  # Updated image name and tag
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://your-mongodb-service-name:27017/your-database-name"
